module MinardDB.Alloy.Generate
  ( generate
  , generateWith
  , validityBanner
  , propertyBanner
  ) where

import Prelude

import Data.Array (filter, null, nub, sort)
import Data.Array as Array
import Data.Foldable (intercalate)
import Data.Maybe (Maybe(..))
import Data.Set (Set)
import Data.Set as Set
import MinardDB.Alloy.Names (fieldName, sigName)
import MinardDB.Properties (Property, defaultProperties, defaultScope, renderCheck)
import MinardDB.Schema (Column, ForeignKey, PGType(..), Schema, Table, UniqueConstraint)

-- | Render a Schema as an Alloy model with the default property catalog.
-- |
-- | The output is structurally partitioned into two sections (after
-- | Kerckhove's `validity`/`genvalidity` insight: property-test
-- | counterexamples must satisfy the input's validity, otherwise you
-- | debug the wrong bug):
-- |
-- |   VALIDITY FACTS — what counts as a meaningful schema instance:
-- |     sigs (atom identity = PK uniqueness), FK field multiplicities
-- |     (target existence), UNIQUE constraints. Always on.
-- |
-- |   PROPERTIES UNDER TEST — independent assertions. Each `check`
-- |     SAT means counterexample found (property fails); UNSAT means
-- |     no counterexample within scope (property holds).
generate :: Schema -> String
generate = generateWith defaultProperties

-- | Render a Schema as an Alloy model with an explicit property list.
-- | Use this when you want a non-default catalog (e.g. for a single-
-- | property smoke test).
generateWith :: Array Property -> Schema -> String
generateWith properties schema =
  let
    primSigs = renderPrimSigs (collectPrimTypes schema)
    tableSigs = map renderTable schema.tables
    uniqueFacts = Array.concatMap renderUniqueFacts schema.tables
    showWitness = "pred show {}\nrun show for " <> show (defaultScope schema)
    checks = properties >>= (_ $ schema)
    propertyTexts = map renderCheck checks
  in
    intercalate "\n\n" $
      [ header schema.name
      , validityBanner
      ]
        <> (if primSigs == "" then [] else [ primSigs ])
        <> tableSigs
        <> uniqueFacts
        <> [ showWitness, propertyBanner ]
        <> propertyTexts

header :: String -> String
header name =
  "// Generated by Minard-DB from schema: " <> name <> "\n"
    <> "// sig <table> { col: <one|lone> <type-or-table> }"

validityBanner :: String
validityBanner =
  "// ─── VALIDITY FACTS (always on) ────────────────────────────────────\n"
    <> "// What counts as a meaningful schema instance:\n"
    <> "//   - sig identity ⇒ PK uniqueness\n"
    <> "//   - FK field `one`/`lone` multiplicity ⇒ FK target existence\n"
    <> "//   - explicit `fact` blocks below ⇒ declared UNIQUE constraints\n"
    <> "// `run show` proves the validity is satisfiable (non-vacuous)."

propertyBanner :: String
propertyBanner =
  "// ─── PROPERTIES UNDER TEST ─────────────────────────────────────────\n"
    <> "// Each `check` below is an independent property. SAT means Alloy\n"
    <> "// found a counterexample (the property is violated); UNSAT means\n"
    <> "// no counterexample exists within the bounded scope (the property\n"
    <> "// holds, with the honest caveat \"checked up to scope N\")."

-- | Collect every primitive PG type referenced by a non-PK, non-FK column.
collectPrimTypes :: Schema -> Set String
collectPrimTypes schema =
  schema.tables
    # Array.concatMap nonRelationalColumns
    # map (\c -> primSigName c.dataType)
    # nub
    # sort
    # Set.fromFoldable

renderPrimSigs :: Set String -> String
renderPrimSigs s =
  let
    names = Set.toUnfoldable s
  in
    if null names then ""
    else intercalate "\n" (map (\n -> "sig " <> n <> " {}") names)

-- | Render one table as a sig with one field per non-PK column.
renderTable :: Table -> String
renderTable t =
  let
    cols = nonRelationalColumns t
    colFields = map (renderColField t) cols
    fkFields = map renderFKField t.foreignKeys
    allFields = colFields <> fkFields
    fieldsStr =
      if null allFields then ""
      else "\n  " <> intercalate ",\n  " allFields <> "\n"
  in
    "sig " <> sigName t.name <> " {" <> fieldsStr <> "}"

-- | Columns that are neither PKs nor part of any FK.
-- | (PKs are implicit in atom identity; FKs are rendered separately.)
nonRelationalColumns :: Table -> Array Column
nonRelationalColumns t =
  let
    pkSet = Set.fromFoldable t.primaryKey
    fkColSet = Set.fromFoldable $ Array.concatMap _.columns t.foreignKeys
    excluded = Set.union pkSet fkColSet
  in
    filter (\c -> not (Set.member c.name excluded)) t.columns

renderColField :: Table -> Column -> String
renderColField _ c =
  fieldName c.name <> ": " <> mult c.nullable <> " " <> primSigName c.dataType

renderFKField :: ForeignKey -> String
renderFKField fk =
  let
    fname = case Array.head fk.columns of
      Just c -> fieldName c
      Nothing -> "fk"
  in
    fname <> ": one " <> sigName fk.refTable

-- | Generate uniqueness facts for each UNIQUE constraint.
renderUniqueFacts :: Table -> Array String
renderUniqueFacts t = map (renderUniqueFact t) t.uniqueConstraints

renderUniqueFact :: Table -> UniqueConstraint -> String
renderUniqueFact t uc =
  let
    -- Qualify the sig with `this/` to disambiguate from any field of
    -- the same name (e.g. Marginalia has `tags` as both a sig and a
    -- field on `project_with_tags`).
    sig = "this/" <> sigName t.name
    factName = "Unique_" <> t.name <> "_" <> intercalate "_" uc.columns
    comparisons = map (\c -> "a." <> fieldName c <> " != b." <> fieldName c) uc.columns
    body = intercalate " or " comparisons
  in
    "fact " <> factName <> " {\n"
      <> "  all disj a, b: " <> sig <> " | " <> body <> "\n"
      <> "}"

mult :: Boolean -> String
mult nullable = if nullable then "lone" else "one"

-- | The Alloy sig name we use for a given PG type, since Alloy is untyped.
primSigName :: PGType -> String
primSigName = case _ of
  PGInt -> "Prim_INTEGER"
  PGBigInt -> "Prim_BIGINT"
  PGText -> "Prim_TEXT"
  PGVarchar _ -> "Prim_VARCHAR"
  PGBoolean -> "Prim_BOOLEAN"
  PGTimestamp -> "Prim_TIMESTAMP"
  PGDate -> "Prim_DATE"
  PGUUID -> "Prim_UUID"
  PGJsonb -> "Prim_JSONB"
