module MinardDB.Alloy.Generate where

import Prelude

import Data.Array (filter, null, nub, sort)
import Data.Array as Array
import Data.Foldable (intercalate)
import Data.Maybe (Maybe(..))
import Data.Set (Set)
import Data.Set as Set
import Data.String.CodeUnits as CodeUnits
import MinardDB.Schema (Column, ForeignKey, PGType(..), Schema, Table, UniqueConstraint)

-- | Render a Schema as an Alloy model.
-- |
-- | Mapping strategy:
-- |   table  -> sig (each Alloy atom represents a row; identity is implicit)
-- |   PK     -> not rendered as a field (atom identity covers it)
-- |   FK col -> relational field pointing at the referenced sig
-- |   other  -> field pointing at a primitive atom sig (Prim_INTEGER, etc.)
-- |   nullable -> `lone` (zero-or-one) multiplicity, else `one`
-- |   UNIQUE constraint -> `fact { all disj a, b: T | a.col != b.col }`
generate :: Schema -> String
generate schema =
  let
    primSigs = renderPrimSigs (collectPrimTypes schema)
    tableSigs = map renderTable schema.tables
    uniqueFacts = Array.concatMap renderUniqueFacts schema.tables
    commands = defaultCommands schema
  in
    intercalate "\n\n" $
      [ header schema.name ]
        <> (if primSigs == "" then [] else [ primSigs ])
        <> tableSigs
        <> uniqueFacts
        <> [ commands ]

header :: String -> String
header name =
  "// Generated by Minard-DB from schema: " <> name <> "\n"
    <> "// sig <table> { col: <one|lone> <type-or-table> }"

-- | Collect every primitive PG type referenced by a non-PK, non-FK column.
collectPrimTypes :: Schema -> Set String
collectPrimTypes schema =
  schema.tables
    # Array.concatMap nonRelationalColumns
    # map (\c -> primSigName c.dataType)
    # nub
    # sort
    # Set.fromFoldable

renderPrimSigs :: Set String -> String
renderPrimSigs s =
  let
    names = Set.toUnfoldable s
  in
    if null names then ""
    else intercalate "\n" (map (\n -> "sig " <> n <> " {}") names)

-- | Render one table as a sig with one field per non-PK column.
renderTable :: Table -> String
renderTable t =
  let
    cols = nonRelationalColumns t
    colFields = map (renderColField t) cols
    fkFields = map renderFKField t.foreignKeys
    allFields = colFields <> fkFields
    fieldsStr =
      if null allFields then ""
      else "\n  " <> intercalate ",\n  " allFields <> "\n"
  in
    "sig " <> sigName t.name <> " {" <> fieldsStr <> "}"

-- | Columns that are neither PKs nor part of any FK.
-- | (PKs are implicit in atom identity; FKs are rendered separately.)
nonRelationalColumns :: Table -> Array Column
nonRelationalColumns t =
  let
    pkSet = Set.fromFoldable t.primaryKey
    fkColSet = Set.fromFoldable $ Array.concatMap _.columns t.foreignKeys
    excluded = Set.union pkSet fkColSet
  in
    filter (\c -> not (Set.member c.name excluded)) t.columns

renderColField :: Table -> Column -> String
renderColField _ c =
  fieldName c.name <> ": " <> mult c.nullable <> " " <> primSigName c.dataType

renderFKField :: ForeignKey -> String
renderFKField fk =
  -- Use the first FK column's name as the field name (composite FK gets first column)
  let
    fname = case Array.head fk.columns of
      Just c -> fieldName c
      Nothing -> "fk"
  in
    fname <> ": one " <> sigName fk.refTable

-- | Generate uniqueness facts for each UNIQUE constraint.
renderUniqueFacts :: Table -> Array String
renderUniqueFacts t = map (renderUniqueFact t) t.uniqueConstraints

renderUniqueFact :: Table -> UniqueConstraint -> String
renderUniqueFact t uc =
  let
    -- Qualify the sig with `this/` to disambiguate from any field of
    -- the same name (e.g. Marginalia has `tags` as both a sig and a
    -- field on `project_with_tags`).
    sig = "this/" <> sigName t.name
    factName = "Unique_" <> t.name <> "_" <> intercalate "_" uc.columns
    comparisons = map (\c -> "a." <> fieldName c <> " != b." <> fieldName c) uc.columns
    body = intercalate " or " comparisons
  in
    "fact " <> factName <> " {\n"
      <> "  all disj a, b: " <> sig <> " | " <> body <> "\n"
      <> "}"

-- | Default commands: run-show (any valid instance) + acyclicity check.
defaultCommands :: Schema -> String
defaultCommands schema =
  let
    n = Array.length schema.tables
    scope = max 3 (min 8 (n + 2))
    scopeStr = show scope
  in
    intercalate "\n\n"
      [ "pred show {}"
      , "run show for " <> scopeStr
      , noFKCycleAssert schema scopeStr
      ]

-- | Assert: no atom is in its own transitive closure across the union
-- | of all FK fields. UNSAT means "no counterexample within scope"
-- | i.e. the property holds. SAT means Alloy found a cycle.
-- |
-- | FK field names can collide across tables (e.g. `declaration_id` may
-- | exist on `child_declarations` AND `declaration_metrics`), so we
-- | qualify each with its owning sig via `<:` (domain restriction).
noFKCycleAssert :: Schema -> String -> String
noFKCycleAssert schema scopeStr =
  let
    qualified = collectQualifiedFKFields schema
  in
    if null qualified then
      "// (no FK fields; acyclicity trivially holds)"
    else
      let
        rendered = map (\{ sig, field } -> "(" <> sig <> " <: " <> field <> ")") qualified
        unioned = intercalate " + " rendered
      in
        "assert NoFKCycle {\n"
          <> "  no a: univ | a in a.^(" <> unioned <> ")\n"
          <> "}\n"
          <> "check NoFKCycle for " <> scopeStr

-- | Collect the (sig, field) pairs for each FK in the schema, ensuring
-- | uniqueness even when the same field name appears on multiple sigs.
collectQualifiedFKFields :: Schema -> Array { sig :: String, field :: String }
collectQualifiedFKFields schema =
  schema.tables
    # Array.concatMap
        (\t -> Array.mapMaybe
                 (\fk -> map (\c -> { sig: sigName t.name, field: fieldName c })
                             (Array.head fk.columns))
                 t.foreignKeys)
    # nub
  where
    -- Local-scoped nub by structural equality
    nub :: Array { sig :: String, field :: String } -> Array { sig :: String, field :: String }
    nub = Array.nubBy (\a b -> compare a.sig b.sig <> compare a.field b.field)

-- Naming helpers -------------------------------------------------------------

-- | Alloy sig names must be valid identifiers. Replace non-alphanumerics
-- | with underscores and capitalize the first letter as a convention.
sigName :: String -> String
sigName = sanitize

fieldName :: String -> String
fieldName = sanitize

sanitize :: String -> String
sanitize s =
  CodeUnits.fromCharArray (map replace (CodeUnits.toCharArray s))
  where
    replace c =
      if isAlphaNumOrUnderscore c then c else '_'

isAlphaNumOrUnderscore :: Char -> Boolean
isAlphaNumOrUnderscore c =
  (c >= 'a' && c <= 'z')
    || (c >= 'A' && c <= 'Z')
    || (c >= '0' && c <= '9')
    || c == '_'

mult :: Boolean -> String
mult nullable = if nullable then "lone" else "one"

-- | The Alloy sig name we use for a given PG type, since Alloy is untyped.
primSigName :: PGType -> String
primSigName = case _ of
  PGInt -> "Prim_INTEGER"
  PGBigInt -> "Prim_BIGINT"
  PGText -> "Prim_TEXT"
  PGVarchar _ -> "Prim_VARCHAR"
  PGBoolean -> "Prim_BOOLEAN"
  PGTimestamp -> "Prim_TIMESTAMP"
  PGDate -> "Prim_DATE"
  PGUUID -> "Prim_UUID"
  PGJsonb -> "Prim_JSONB"
