-- | Schema **V2** — the "after" of the migration: regenerated by the same
-- | rung-1 codegen from a DDL that has **dropped the `email` column**.
-- |
-- | This is a *valid, usable* schema — queries that never reached `email`
-- | still compile against it unchanged (see `Queries.userAgesV2`). The
-- | migration didn't break everything; it broke exactly the queries that
-- | depended on the dropped column, and the compiler tells you which ones
-- | and where. The proof that it breaks `userContacts` lives in
-- | `bridge/compile-fail-tests/MigrationBreaksQuery.purs`.
module Minard.Bridge.Migration.SchemaV2 where

import Type.Proxy (Proxy(..))
import Yoga.Postgres.Schema (Table, PrimaryKey, Nullable)

type UsersTable = Table "users"
  ( id :: PrimaryKey Int
  , name :: String
  , age :: Nullable Int
  )

usersTable :: Proxy UsersTable
usersTable = Proxy
